services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    ports:
      - '8096:8096'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/e/YT_Vids/
        target: /media
        read_only: true
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
