version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest-ultra-lite
    ports:
      - '8080:8081'
    volumes:
      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=vi_VN
