services:
  glance:
    image: glanceapp/glance
    volumes:
      - ./glance.yaml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8082:8080
    restart: unless-stopped
