services:
  glance:
    image: glanceapp/glance
    volumes:
      - ./glance.yaml:/app/glance.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8082
    restart: unless-stopped
